
name: MLOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Set up Kaggle API credentials
      run: |
        mkdir -p ~/.kaggle
        echo "{\"username\":\"${{ secrets.KAGGLE_USERNAME }}\",\"key\":\"${{ secrets.KAGGLE_KEY }}\"}" > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json
    - name: Create required directories
      run: |
        mkdir -p logs data/raw data/processed data/validation
    - name: Run Data Ingestion Test
      run: |
        python src/ingest_data.py
    - name: Run Data Splitting Test
      run: |
        python src/data_splitter.py
    - name: Test with pytest
      run: |
        pytest

  run_pipeline:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Set up Kaggle API credentials
      run: |
        mkdir -p ~/.kaggle
        echo "{\"username\":\"${{ secrets.KAGGLE_USERNAME }}\",\"key\":\"${{ secrets.KAGGLE_KEY }}\"}" > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json
    - name: Create required directories
      run: |
        mkdir -p logs data/raw data/processed data/validation
    - name: Run MLOps Pipeline - Data Ingestion
      run: |
        python pipeline.py --phase 1
    - name: Run MLOps Pipeline - Data Splitting
      run: |
        python pipeline.py --phase 2
